### ISSUE TITLE
Tracking issue for redesign

### ISSUE THREAD

**Issue by willcrichton** [scanner-research/vgrid#3]
- [x] Undo stack
- [x] Bounding box labeling
- [x] Performance issues 
- [x] Settings
- [x] Jupyter keybindings
- [ ] Crop images
- [x] Gender/identity (categorical) metadata on bboxes
- [ ] Labeling multiple interval sets simultaneously (e.g. conversations and scenes)
- [x] Poses and face keypoints
- [ ] Custom block level metadata (e.g. indicate which frame is a boundary)
- [x] On-demand non-interval metadata (e.g. video name, frame number)
